### ISSUE TITLE
Diagonal words in the Suchsel are not working ;-(

### ISSUE THREAD

**Issue by Julaja** [johndoe31415/pysuchsel#1]
./pysuchsel -p dbr -v -x 22 -y 22 words.txt suchsel_Laborgeräte2.svg
Traceback (most recent call last):
  File "./pysuchsel", line 70, in <module>
    placed = suchsel.place(word, contiguous = args.contiguous)
  File "/home/julia/pysuchsel/Suchsel.py", line 181, in place
    if self._attempt_place(word):
  File "/home/julia/pysuchsel/Suchsel.py", line 159, in _attempt_place
    for (adjx, adjy) in self._adjacent_fields(x, y, rule):
  File "/home/julia/pysuchsel/Suchsel.py", line 90, in _adjacent_fields
    raise NotImplementedError(rulename)
NotImplementedError: dbr

**Comment by Julaja** [comment]
By the way I am a fan of Pysuchsel!

**Comment by johndoe31415** [comment]
I am a fan of you, @Julaja <3 <3 <3 :-)

Fixed your bug!
